name: ttt_merchant_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.16+23

environment:
  sdk: ^3.9.0

dependencies:
  after_layout: ^1.2.0
  dio: ^5.9.0
  dropdown_button2: ^2.3.9
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.1
  flutter_svg: ^2.2.0
  form_builder_validators: ^11.2.0
  get_it: ^8.2.0
  google_fonts: ^6.3.1
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  pinput: ^5.0.1
  provider: ^6.1.5+1
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  upgrader: ^12.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ios_icon.png"

flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/images/
      - assets/svg/
      - assets/icon/
      # - assets/lottie/
